name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:
jobs:
  test:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - name: Run tests
        run: go test -v ./...

  build:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - name: Criar environment
        run: |
          touch .env
          echo "${{ secrets.APP_KEY }}" > .env
          cat .env
      - name: Buildar aplicacao
        run: docker build --network=host -t kaduhod/fin .
      - name: Subir build
        run: docker push kaduhod/fin
  deploy:
    needs: build
    runs-on: [ self-hosted, linux ]
    steps:
      - name:
        run: chmod +x deploy.dev.sh
      - name: Deploy
        run: ./deploy.dev.sh
