name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:
jobs:
  build:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: "Initialize app"
        run: go run . artisan key:generate
      - name: Buildar aplicacao
        run: docker build --network=host -t kaduhod/fin .
      - name: Subir build
        run: docker push kaduhod/fin
  deploy:
    needs: build
    runs-on: [ self-hosted, linux ]
    steps:
      - name:
        run: chmod +x deploy.dev.sh
      - name: Deploy
        run: ./deploy.dev.sh

