name: CI
on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

  workflow_dispatch:
jobs:
  deploy:
    runs-on: [ self-hosted, linux ]
    steps:
      - name:
        run: chmod +x deploy.prod.sh
      - name: Deploy
        run: ./deploy.prod.sh

